apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  template:
    spec:
      containers:
        - name: catalog-api
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
spec:
  template:
    spec:
      containers:
        - name: inventory-api
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  template:
    spec:
      containers:
        - name: orders-api
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
spec:
  template:
    spec:
      containers:
        - name: payments-api
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-api
spec:
  template:
    spec:
      containers:
        - name: edge-api
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-web
spec:
  template:
    spec:
      containers:
        - name: shop-web
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coach
spec:
  template:
    spec:
      containers:
        - name: coach
          imagePullPolicy: Always
