apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: cloudtracing/catalog
    newName: localhost:30300/cloudtracing/catalog
    newTag: latest
  - name: cloudtracing/inventory
    newName: localhost:30300/cloudtracing/inventory
    newTag: latest
  - name: cloudtracing/orders
    newName: localhost:30300/cloudtracing/orders
    newTag: latest
  - name: cloudtracing/payments
    newName: localhost:30300/cloudtracing/payments
    newTag: latest
  - name: cloudtracing/edge
    newName: localhost:30300/cloudtracing/edge
    newTag: latest
  - name: cloudtracing/shop-web
    newName: localhost:30300/cloudtracing/shop-web
    newTag: latest
  - name: cloudtracing/coach
    newName: localhost:30300/cloudtracing/coach
    newTag: latest

patches:
  - path: image-pull-policy.yaml
  - path: localhost-ports.yaml
  - path: hostport-recreate.yaml
